import { OekoPlanning } from './oeko-planning';
import { useState, type ReactNode } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { Activity, Archive, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, CalendarDays, ChartNoAxesCombined, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Download, Ellipsis, FileText, Filter, House, Images, Inbox, Layers3, LayoutDashboard, LogOut, Megaphone, Menu, Newspaper, PanelLeftOpen, PanelLeftClose, Plus, PlugZap, ScrollText, Search, Settings2, Sun, TrendingUp, Upload, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { leads as seedLeads, navGroups, pathFor, services, articles, type Lead, type View } from '@/lib/oeko-data';
import { useOekoDemo } from '@/lib/oeko-demo';
import { OekoSubpage } from '@/components/oeko-subpage';
import { OekoQualification } from '@/components/oeko-qualification';
import { OekoDashboard } from '@/components/oeko-dashboard';
import { OekoDossiers } from '@/components/oeko-dossiers';
import { OekoDay } from '@/components/oeko-day';
import { OekoSeo } from '@/components/oeko-seo';
import chantierImage from '@/assets/chantier-facade.jpg';
import oekoLogo from '@/assets/oeko-logo.jpg.asset.json';

const icons = { LayoutDashboard, Sun, Inbox, Users, CalendarDays, FileText, Newspaper, Layers3, House, Images, Megaphone, ChartNoAxesCombined, Settings2, PlugZap, ScrollText, TrendingUp };
const titles: Record<View,string> = {dashboard:'Tableau de bord',qualification:'Qualification',dossiers:'Dossiers CRM',journee:'Ma journée',planning:'Planning',devis:'Devis & ventes',articles:'Articles / Blog',services:'Services',realisations:'Réalisations',mediatheque:'Médiathèque',marketing:'Marketing',seo:'SEO & Acquisition',performance:'Performance commerciale',parametres:'Paramètres',integrations:'Intégrations & erreurs',journal:'Journal d’activité'};
const descriptions: Partial<Record<View,string>> = {dashboard:'Votre activité en un coup d’œil.',qualification:'Suivez et qualifiez les nouvelles demandes.',dossiers:'Tous vos prospects, au même endroit.',journee:'Vos priorités pour aujourd’hui.',planning:'Organisez vos rendez-vous.',devis:'Suivez vos propositions commerciales.',articles:'Gérez les contenus de votre site.',services:'Présentez vos expertises.',realisations:'Valorisez vos chantiers.',mediatheque:'Vos images et documents.',marketing:'Comprenez l’origine de vos opportunités.',seo:'Vos KPI Google Analytics et Search Console.',performance:'Suivez les résultats de l’équipe.'};
type Row = {name:string; detail:string; date:string; status:string; extra:string};
const statusClass = (s:string) => s === 'Publié' || s === 'Accepté' || s === 'Qualifié' || s === 'Connecté' || s === 'Vente' ? 'bg-lime/35 text-foreground' : s === 'À qualifier' || s === 'À relancer' || s === 'En erreur' || s === 'En retard' ? 'bg-secondary text-primary' : 'bg-muted text-muted-foreground';
function Badge({children}:{children:ReactNode}){return <span className={`inline-flex w-fit items-center rounded px-2.5 py-1 text-[11px] font-semibold whitespace-nowrap ${statusClass(String(children))}`}>{children}</span>}
function Box({title, action, children, className=''}:{title:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`min-w-0 rounded-lg border border-border bg-card ${className}`}><div className="flex items-center justify-between gap-3 border-b border-border px-5 py-4"><h2 className="text-sm font-bold">{title}</h2>{action}</div>{children}</section>}
function Empty({text='Aucun résultat pour cette recherche.'}:{text?:string}){return <div className="p-12 text-center text-sm text-muted-foreground">{text}</div>}
function Bars({values, labels, color='primary'}:{values:number[];labels:string[];color?:'primary'|'lime'}){return <div className="flex h-40 items-end justify-between gap-2 pt-4">{values.map((n,i)=><div key={i} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><div className={`w-full max-w-9 rounded-t-sm ${color==='lime'?'bg-lime':'bg-primary'}`} style={{height:`${n}%`}}/><span className="text-[10px] text-muted-foreground">{labels[i]}</span></div>)}</div>}
function DataTable({headers,rows,onRow}:{headers:string[];rows:{cells:ReactNode[];key:string}[];onRow?:(key:string)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="bg-canvas">{headers.map(h=><th key={h} className="px-5 py-3 text-[11px] font-semibold uppercase text-muted-foreground">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.key} onClick={()=>onRow?.(r.key)} className={`border-t border-border ${onRow?'cursor-pointer hover:bg-canvas':''}`}>{r.cells.map((cell,i)=><td key={i} className="px-5 py-3.5 text-xs text-foreground">{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>}
function Label({children}:{children:ReactNode}){return <label className="mb-1.5 block text-xs font-semibold text-foreground">{children}</label>}
function Field({label,placeholder='',type='text',defaultValue='',options,wide=false}:{label:string;placeholder?:string;type?:string;defaultValue?:string;options?:string[];wide?:boolean}){return <div className={wide?'sm:col-span-2':''}><Label>{label}</Label>{type==='textarea'?<Textarea placeholder={placeholder} defaultValue={defaultValue} className="min-h-24 bg-background"/>:options?<select defaultValue={defaultValue||options[0]} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm">{options.map(v=><option key={v}>{v}</option>)}</select>:<Input type={type} placeholder={placeholder} defaultValue={defaultValue} className="bg-background"/>}</div>}
export function OekoWorkspace({view,subpage}:{view:View;subpage?:{section:string;item:string}}){
  const {leadList,entries,desktopMenuOpen,setDesktopMenuOpen,quoteList,log,addLog,notifs,markNotif,markAllNotifs,setPrefillLeadId}=useOekoDemo();
 const [settingsGroup,setSettingsGroup]=useState(''),[extraSettings,setExtraSettings]=useState<Record<string,string[]>>({}),[settingsDraft,setSettingsDraft]=useState(''),[errorRow,setErrorRow]=useState(''),[errorStates,setErrorStates]=useState<Record<string,string>>({});
 const [mobileOpen,setMobileOpen]=useState(false),[logged,setLogged]=useState(true),[role,setRole]=useState('Administrateur');
 const [authStep,setAuthStep]=useState<'login'|'reset'|'sent'>('login'),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(''),[authEmail,setAuthEmail]=useState(''),[authPass,setAuthPass]=useState(''),[resetEmail,setResetEmail]=useState('');
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('Tous les statuts'),[sourceFilter,setSourceFilter]=useState('Toutes les sources'),[serviceFilter,setServiceFilter]=useState('Tous les services');
 const [globalQ,setGlobalQ]=useState(''),[globalOpen,setGlobalOpen]=useState(false),[notifOpen,setNotifOpen]=useState(false),[devisTab,setDevisTab]=useState<'Devis'|'Ventes'|'Pertes'>('Devis'),[journalQ,setJournalQ]=useState(''),[journalUser,setJournalUser]=useState('Tous les utilisateurs'),[journalAction,setJournalAction]=useState('Toutes les actions'),[retryState,setRetryState]=useState<Record<string,string>>({});
 const [disabled,setDisabled]=useState<string[]>([]),[mediaArchived,setMediaArchived]=useState<string[]>([]),[mediaUse,setMediaUse]=useState('Article de blog');
 const [modal,setModal]=useState<string|null>(null),[toast,setToast]=useState(''),[calendarMode,setCalendarMode]=useState('Semaine'),[offset,setOffset]=useState(0),[mediaNames,setMediaNames]=useState(['Rénovation façade - Créteil','Isolation extérieure - Versailles','Chantier toiture - Montreuil','Pompe à chaleur - Yvelines','Façade rénovée - Val-de-Marne','Maison rénovée - Essonne']),[mediaIndex,setMediaIndex]=useState<number|null>(null),[mediaDraft,setMediaDraft]=useState(''),[mediaAlt,setMediaAlt]=useState('');
 const navigate=useNavigate();
 const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),3300)};
 const unread=notifs.filter(n=>!n.read).length;
 const gq=globalQ.trim().toLowerCase();
 const globalLeads=gq?leadList.filter(l=>`${l.name} ${l.phone} ${l.email} ${l.address} ${l.city} ${l.zip} ${l.id}`.toLowerCase().includes(gq)).slice(0,6):[];
 const globalQuotes=gq?quoteList.filter(q=>`${q.ref} ${q.name} ${q.service}`.toLowerCase().includes(gq)).slice(0,4):[];
 const journalRows=log.filter(r=>`${r.action} ${r.target} ${r.user}`.toLowerCase().includes(journalQ.toLowerCase())&&(journalUser==='Tous les utilisateurs'||r.user===journalUser)&&(journalAction==='Toutes les actions'||r.action===journalAction));
 const sales=leadList.filter(l=>['Vente','Signé'].includes(l.status));
 const losses=leadList.filter(l=>['Perdu','Abandon','Inexploitable'].includes(l.status));
 const filtered=leadList.filter(l=>`${l.name} ${l.city} ${l.service} ${l.id}`.toLowerCase().includes(search.toLowerCase())&&(filter==='Tous les statuts'||l.status===filter)&&(sourceFilter==='Toutes les sources'||l.source===sourceFilter)&&(serviceFilter==='Tous les services'||l.service===serviceFilter));
 const openSubpage=(section:string,item:string)=>navigate({to:`/${section}/${encodeURIComponent(item)}`});
 const openLead=(lead:Lead)=>openSubpage(view==='qualification'?'qualification':'dossiers',lead.id);
 const topAction = ({articles:['Ajouter un article','article'],services:['Ajouter un service','service'],realisations:['Ajouter une réalisation','realisation'],planning:['Nouveau rendez-vous','rdv'],devis:['Nouveau devis','devis']} as Partial<Record<View,string[]>>)[view];
  const nav=<><div className="flex h-18 items-center justify-between border-b border-border px-6"><Link to="/" onClick={()=>setMobileOpen(false)} className="flex items-center gap-2.5"><img src={oekoLogo.url} alt="OEKO" className="size-9 rounded object-cover"/><span className="text-[22px] font-extrabold tracking-normal text-foreground">OEKO</span></Link><Button size="icon" variant="ghost" className="lg:hidden" onClick={()=>setMobileOpen(false)} aria-label="Fermer le menu"><X/></Button><Button size="icon" variant="ghost" className="hidden lg:inline-flex" onClick={()=>setDesktopMenuOpen(false)} aria-label="Masquer le menu" title="Masquer le menu"><PanelLeftClose size={19}/></Button></div><div className="flex-1 overflow-y-auto px-3 py-5">{navGroups.map(group=><div key={group.label} className="mb-6"><p className="px-3 pb-2 text-[10px] font-bold text-muted-foreground">{group.label}</p><div className="space-y-0.5">{group.items.map(item=>{const Icon=icons[item.icon as keyof typeof icons];return <Link key={item.view} to={pathFor(item.view)} onClick={()=>{setMobileOpen(false);setSearch('');setSearch('')}} className={`flex h-10 items-center gap-3 rounded-md px-3 text-[13px] font-medium transition-colors ${view===item.view?'bg-primary text-primary-foreground':'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon size={17}/><span>{item.label}</span>{item.view==='qualification'&&<span className={`ml-auto rounded px-1.5 py-0.5 text-[10px] font-bold ${view===item.view?'bg-lime text-lime-foreground':'bg-lime/50 text-foreground'}`}>4</span>}</Link>})}</div></div>)}</div><div className="border-t border-border p-4"><div className="flex items-center gap-3 rounded-md bg-canvas p-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">AM</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">Alexandre Martin</div><div className="truncate text-[11px] text-muted-foreground">{role}</div></div><Button variant="ghost" size="icon" aria-label="Se déconnecter" title="Se déconnecter" onClick={()=>setLogged(false)}><LogOut size={16}/></Button></div></div></>;
 if(!logged)return <div className="flex min-h-screen items-center justify-center bg-canvas p-5"><div className="w-full max-w-sm rounded-lg border border-border bg-background p-8 shadow-sm"><div className="mb-9 flex items-center gap-2.5"><img src={oekoLogo.url} alt="OEKO" className="size-10 rounded object-cover"/><span className="text-2xl font-extrabold">OEKO</span></div><h1 className="text-2xl font-bold">Bon retour parmi nous.</h1><p className="mt-2 text-sm text-muted-foreground">Connectez-vous à votre espace OEKO.</p><form className="mt-8 space-y-4" onSubmit={e=>{e.preventDefault();setLogged(true);notify('Bienvenue sur votre espace de démonstration.')}}><div><Label>Adresse e-mail</Label><Input required type="email" placeholder="vous@oeko.fr"/></div><div><Label>Mot de passe</Label><Input required type="password" placeholder="••••••••"/></div><Button className="w-full">Se connecter <ArrowRight size={16}/></Button></form><p className="mt-7 text-center text-xs text-muted-foreground">Aperçu interactif · saisissez un email et un mot de passe</p></div></div>;
  return <div className={`min-h-screen bg-canvas text-foreground transition-[padding] duration-200 motion-reduce:transition-none ${desktopMenuOpen?'lg:pl-[238px]':''}`}><aside className={`fixed inset-y-0 left-0 z-40 hidden w-[238px] flex-col border-r border-border bg-background ${desktopMenuOpen?'lg:flex':''}`}>{nav}</aside>{mobileOpen&&<><div onClick={()=>setMobileOpen(false)} className="fixed inset-0 z-40 bg-foreground/35 lg:hidden"/><aside className="fixed inset-y-0 left-0 z-50 flex w-[min(85vw,260px)] flex-col bg-background shadow-xl lg:hidden">{nav}</aside></>}
  <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background px-4 sm:px-7"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" className="shrink-0 lg:hidden" onClick={()=>setMobileOpen(true)} aria-label="Ouvrir le menu"><Menu/></Button>{!desktopMenuOpen&&<Button variant="ghost" size="icon" className="hidden shrink-0 lg:inline-flex" onClick={()=>setDesktopMenuOpen(true)} aria-label="Afficher le menu" title="Afficher le menu"><PanelLeftOpen size={19}/></Button>}<div className="relative hidden md:block"><Search size={15} className="absolute left-3 top-2.5 text-muted-foreground"/><Input value={globalQ} onChange={e=>{setGlobalQ(e.target.value);setGlobalOpen(true)}} onFocus={()=>setGlobalOpen(true)} placeholder="Rechercher un dossier, un téléphone, un devis…" className="w-72 pl-9 xl:w-96"/>
  {globalOpen&&globalQ.trim().length>0&&<div className="absolute left-0 top-11 z-50 w-[min(92vw,420px)] overflow-hidden rounded-lg border border-border bg-background shadow-xl">
    {globalLeads.length+globalQuotes.length===0?<div className="p-5 text-center text-xs text-muted-foreground">Aucun résultat pour « {globalQ} ».<button onClick={()=>{setGlobalQ('');setGlobalOpen(false)}} className="mt-2 block w-full font-semibold text-primary">Réinitialiser la recherche</button></div>:<ul className="max-h-80 divide-y divide-border overflow-y-auto">
      {globalLeads.map(l=><li key={l.id}><button onClick={()=>{setGlobalOpen(false);setGlobalQ('');openSubpage('dossiers',l.id)}} className="flex w-full flex-col px-4 py-2.5 text-left hover:bg-canvas"><span className="text-xs font-bold">{l.name} · {l.id}</span><span className="text-[11px] text-muted-foreground">{l.phone} · {l.email} · {l.address}, {l.zip} {l.city}</span></button></li>)}
      {globalQuotes.map(q=><li key={q.ref}><button onClick={()=>{setGlobalOpen(false);setGlobalQ('');openSubpage('devis',q.ref)}} className="flex w-full flex-col px-4 py-2.5 text-left hover:bg-canvas"><span className="text-xs font-bold">{q.ref} · {q.total}</span><span className="text-[11px] text-muted-foreground">Devis · {q.name} · {q.service}</span></button></li>)}
    </ul>}</div>}</div><div className="min-w-0 text-xs text-muted-foreground">Espace OEKO <span className="mx-2">/</span> <span className="truncate font-semibold text-foreground">{subpage ? subpage.item==='nouveau'?'Créer':subpage.item : titles[view]}</span></div></div><div className="flex items-center gap-2 sm:gap-4"><span className="hidden items-center gap-2 rounded-full bg-lime/35 px-3 py-1.5 text-[11px] font-semibold sm:inline-flex"><span className="size-1.5 rounded-full bg-lime-foreground"/> Démonstration</span><div className="relative"><Button variant="ghost" size="icon" aria-label="Notifications" title="Notifications" onClick={()=>setNotifOpen(o=>!o)}><Bell size={18}/>{unread>0&&<span className="absolute -right-0.5 -top-0.5 flex size-4 items-center justify-center rounded-full bg-destructive text-[9px] font-bold text-destructive-foreground">{unread}</span>}</Button>
  {notifOpen&&<div className="absolute right-0 top-11 z-50 w-[min(92vw,360px)] overflow-hidden rounded-lg border border-border bg-background shadow-xl"><div className="flex items-center justify-between border-b border-border px-4 py-3"><p className="text-xs font-bold">Notifications · {unread} non lues</p><button onClick={()=>{markAllNotifs();notify('Toutes les notifications sont lues.')}} className="text-[11px] font-semibold text-primary">Tout marquer lu</button></div>
  <ul className="max-h-80 divide-y divide-border overflow-y-auto">{notifs.map(n=><li key={n.id}><button onClick={()=>{markNotif(n.id);setNotifOpen(false);const l=leadList.find(x=>x.id===n.leadId);if(l)openLead(l)}} className={`flex w-full gap-2 px-4 py-3 text-left hover:bg-canvas ${n.read?'opacity-55':''}`}><span className={`mt-1.5 size-1.5 shrink-0 rounded-full ${n.read?'bg-muted-foreground':'bg-primary'}`}/><span className="min-w-0"><span className="block text-xs font-bold">{n.title}</span><span className="block text-[11px] text-muted-foreground">{n.body}</span><span className="block text-[10px] text-muted-foreground">{n.when}{n.leadId?` · ${n.leadId}`:''}</span></span></button></li>)}{!notifs.length&&<li className="p-6 text-center text-xs text-muted-foreground">Aucune notification.</li>}</ul></div>}</div><div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary text-[11px] font-bold text-primary-foreground">AM</div></div></header>
  <main>{subpage ? <OekoSubpage section={subpage.section} item={subpage.item} wide={!desktopMenuOpen}/> : <div className={`mx-auto px-4 pb-16 pt-7 sm:px-7 lg:px-9 ${desktopMenuOpen?'max-w-[1600px]':''}`}><div className="mb-7 grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3 sm:flex sm:items-center sm:justify-between"><div className="min-w-0"><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold text-muted-foreground"><span className="size-1.5 rounded-full bg-lime-foreground"/> ESPACE DE TRAVAIL <span>·</span> SEPTEMBRE 2026</div><h1 className="text-2xl font-bold sm:text-[29px]">{titles[view]}</h1><p className="mt-1 text-xs text-muted-foreground sm:text-sm">{descriptions[view]||'Gérez votre espace OEKO en toute simplicité.'}</p></div><div className="flex shrink-0 items-center gap-2">{topAction&&<Button size="sm" onClick={()=>openSubpage(view,'nouveau')} className="h-9 px-2 sm:px-3"><Plus size={16}/><span className="hidden sm:inline">{topAction[0]}</span><span className="sr-only sm:hidden">{topAction[0]}</span></Button>}</div></div>
 {view==='dashboard'&&<OekoDashboard leadList={leadList} openLead={openLead} go={v=>navigate({to:pathFor(v)})} newDossier={()=>openSubpage('dossiers','nouveau')}/>}
 {view==='qualification'&&<OekoQualification openLead={openLead}/>}
{view==='dossiers'&&<OekoDossiers openLead={openLead} newDossier={()=>openSubpage('dossiers','nouveau')}/>}
 {view==='journee'&&<OekoDay leadList={leadList} openLead={openLead} go={v=>navigate({to:pathFor(v)})}/>}
 {view==='planning'&&<OekoPlanning />}
 {view==='devis'&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><MiniStat label="Devis en cours" value={String(quoteList.filter(q=>q.status!=='Accepté'&&q.status!=='Refusé').length)} change={`${quoteList.filter(q=>q.status==='À relancer').length} à relancer`}/><MiniStat label="Ventes enregistrées" value={String(sales.length)} change="Statut Vente"/><MiniStat label="Dossiers perdus" value={String(losses.length)} change="Motifs renseignés"/></div>
 <div className="flex gap-1 rounded-lg bg-muted p-1 sm:w-fit">{(['Devis','Ventes','Pertes'] as const).map(t=><button key={t} onClick={()=>setDevisTab(t)} className={`h-8 flex-1 rounded-md px-4 text-xs font-semibold sm:flex-none ${devisTab===t?'bg-background shadow-sm':'text-muted-foreground'}`}>{t}</button>)}</div>
 {devisTab==='Devis'&&<Box title="Tous les devis" action={<Button size="sm" onClick={()=>openSubpage('devis','nouveau')}><Plus size={15}/>Nouveau devis</Button>}><DataTable headers={['Référence','Date','Prospect','Service','Montant HT','Relance','Statut']} rows={quoteList.map(q=>({key:q.ref,cells:[<span className="font-bold text-primary">{q.ref}</span>,q.date,q.name,q.service,q.amount,q.followUp||'—',<Badge>{q.status}</Badge>]}))} onRow={ref=>openSubpage('devis',ref)}/></Box>}
 {devisTab==='Ventes'&&<Box title="Ventes signées" action={<Button variant="outline" size="sm" onClick={()=>openSubpage('devis','vente')}>Enregistrer une vente</Button>}><DataTable headers={['Client','Service','Montant','Date','Devis concerné','Commercial','Commentaire']} rows={sales.map(l=>({key:l.id,cells:[<span className="font-bold">{l.name}</span>,l.service,l.saleAmount??l.amount,l.saleDate??'—',l.saleQuote||'—',l.owner,l.saleComment||'—']}))} onRow={id=>{const l=leadList.find(x=>x.id===id);if(l){setPrefillLeadId(l.id);openSubpage('dossiers',l.id)}}}/></Box>}
 {devisTab==='Pertes'&&<Box title="Dossiers perdus" action={<Button variant="ghost" size="sm" onClick={()=>openSubpage('devis','perte')}>Déclarer une perte</Button>}><DataTable headers={['Client','Service','Montant','Motif','Concurrent','Date','Commentaire']} rows={losses.map(l=>({key:l.id,cells:[<span className="font-bold">{l.name}</span>,l.service,l.amount,<Badge>{l.lossReason??'À préciser'}</Badge>,l.competitor||'—',l.lossDate??'—',l.lossComment||'—']}))} onRow={id=>{const l=leadList.find(x=>x.id===id);if(l){setPrefillLeadId(l.id);openSubpage('dossiers',l.id)}}}/></Box>}
 <p className="text-[11px] text-muted-foreground">Données de démonstration.</p></div>}

 {view==='articles'&&<ContentList kind="articles" search={search} setSearch={setSearch} openItem={item=>openSubpage(view,item)} entries={entries}/>}
 {view==='services'&&<ContentList kind="services" search={search} setSearch={setSearch} openItem={item=>openSubpage(view,item)} entries={entries}/>}
 {view==='realisations'&&<ContentList kind="realisations" search={search} setSearch={setSearch} openItem={item=>openSubpage(view,item)} entries={entries}/>}
 {view==='mediatheque'&&<div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-muted-foreground" size={16}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un média..." className="pl-9"/></div><select aria-label="Type de média" className="h-9 rounded-md border border-border bg-background px-3 text-xs"><option>Tous les médias</option><option>Images</option><option>Documents</option></select><Button size="sm" onClick={()=>document.getElementById('media-upload')?.click()}><Upload size={15}/> Importer</Button><input id="media-upload" type="file" accept="image/*,.pdf" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file){setMediaNames([...mediaNames,file.name]);notify('Média ajouté à la démonstration.')}}}/></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4">{mediaNames.filter(n=>n.toLowerCase().includes(search.toLowerCase())).map((name,i)=><div key={`${name}-${i}`} onClick={()=>{setMediaIndex(mediaNames.indexOf(name));setMediaDraft(name);setMediaAlt('Maison rénovée en Île-de-France')}} className="cursor-pointer overflow-hidden rounded-lg border border-border bg-background hover:border-primary"><img src={chantierImage} alt={name} width={1200} height={800} loading="lazy" className="aspect-[4/3] w-full object-cover"/><div className="p-3"><p className="truncate text-xs font-bold">{name}</p><p className="mt-1 text-[11px] text-muted-foreground">Image · 1,2 Mo{mediaArchived.includes(name)?' · Archivé':''}</p></div></div>)}</div></div>}
 {view==='marketing'&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><MiniStat label="Leads générés" value="248" change="+18 % ce mois"/><MiniStat label="Leads qualifiés" value="169" change="68 % des leads"/><MiniStat label="CA attribué" value="286 400 €" change="Ce trimestre"/></div><div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Box title="Performance par source"><DataTable headers={['Source','Leads','Qualifiés','RDV','Devis','Ventes','CA']} rows={[['Google Ads','92','61','34','21','8','112 800 €'],['SEO','64','48','27','19','7','89 500 €'],['Meta','38','22','12','8','3','38 200 €'],['Email','25','18','10','7','2','26 400 €'],['Appels','19','14','8','5','1','12 600 €'],['Apporteurs','10','6','4','3','1','6 900 €']].map((r,i)=>({key:String(i),cells:r}))}/></Box><Box title="Répartition des sources"><div className="p-6"><Bars values={[92,64,38,25,19,10]} labels={['Ads','SEO','Meta','Email','Appels','Autres']} color="lime"/><div className="mt-5 text-xs text-muted-foreground">Google Ads représente 37 % des nouveaux leads.</div></div></Box></div></div>}
 {view==='seo'&&<OekoSeo/>}
 {view==='performance'&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><MiniStat label="Ventes ce mois" value="24" change="+12 %"/><MiniStat label="CA signé" value="328 400 €" change="+8,2 %"/><MiniStat label="Taux devis → vente" value="34 %" change="+3,1 %"/></div><Box title="Performance par commercial"><DataTable headers={['Commercial','Leads','RDV','Devis','Ventes','CA','Qualif.','Devis → vente']} rows={[['Laurent Moreau','86','32','25','10','142 500 €','72 %','40 %'],['Sophie Martin','74','29','21','8','109 200 €','69 %','38 %'],['Thomas Leroy','62','24','18','6','76 700 €','65 %','33 %']].map((r,i)=>({key:String(i),cells:r}))}/></Box><div className="grid gap-5 md:grid-cols-2"><Box title="Ventes par commercial"><div className="p-5"><Bars values={[90,72,54]} labels={['Laurent','Sophie','Thomas']}/></div></Box><Box title="Évolution du chiffre d’affaires"><div className="p-5"><Bars values={[42,51,46,67,62,79,92]} labels={['Mar','Avr','Mai','Juin','Juil','Août','Sept']} color="lime"/></div></Box></div></div>}
 {view==='parametres'&&<div className="grid gap-5 lg:grid-cols-2">{[{title:'Utilisateurs & rôles',items:['Alexandre Martin · Administrateur','Émilie Bernard · Qualification / Marketing','Laurent Moreau · Commercial','Sophie Martin · Commercial']},{title:'Services',items:services},{title:'Statuts & motifs de perte',items:['Nouveau · À qualifier · Qualifié · Commercial attribué','À rappeler · RDV planifié · Devis à faire · Devis envoyé','À relancer · Vente · Perdu','Nurserie · Inexploitable · Abandon · Archivé','Trop cher · Concurrent · Projet abandonné','Projet reporté · Hors cible · Raison technique']},{title:'Sources marketing',items:['Google Ads','SEO','Meta','Email','Appels','Apporteurs']},{title:'Modèles SMS / email',items:['Confirmation de rendez-vous · SMS','Rappel de rendez-vous · SMS','Envoi de devis · Email','Relance de devis · Email']}].map(group=><Box key={group.title} title={group.title} action={<Button variant="ghost" size="icon" title={`Modifier ${group.title}`} onClick={()=>{setSettingsGroup(group.title);setSettingsDraft('');setModal('settings')}}><Ellipsis size={18}/></Button>}><div className="divide-y divide-border">{[...group.items,...(extraSettings[group.title]??[])].map(item=>{const off=disabled.includes(item);return <div key={item} className="flex items-center justify-between gap-3 px-5 py-3 text-xs"><span className={off?'text-muted-foreground line-through':''}>{item}</span><button onClick={()=>{setDisabled(p=>off?p.filter(x=>x!==item):[...p,item]);addLog(off?'A restauré un paramètre':'A désactivé un paramètre',item);notify(off?'Élément restauré.':'Élément désactivé.')}} className="shrink-0 font-semibold text-primary">{off?'Restaurer':'Désactiver'}</button></div>})}{![...group.items,...(extraSettings[group.title]??[])].length&&<p className="p-6 text-center text-xs text-muted-foreground">Aucun élément pour le moment.</p>}</div></Box>)}<Box title="Rôle de démonstration"><div className="p-5"><Label>Voir l’espace comme</Label><select value={role} onChange={e=>{setRole(e.target.value);notify(`Aperçu du rôle ${e.target.value}.`)}} className="h-9 w-full rounded-md border border-border bg-background px-3 text-sm">{['Administrateur','Qualification / Marketing','Commercial'].map(r=><option key={r}>{r}</option>)}</select></div></Box></div>}
 {view==='integrations'&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{['Formulaires du site','Google Ads','Meta Lead Ads'].map((s,i)=><div key={s} className="rounded-lg border border-border bg-background p-5"><div className="flex items-center justify-between"><PlugZap size={18} className="text-primary"/><Badge>{i===2?'En erreur':'Connecté'}</Badge></div><p className="mt-6 text-sm font-bold">{s}</p><p className="mt-1 text-xs text-muted-foreground">{i===2?'Dernière synchronisation : 23 sept.':'Synchronisé aujourd’hui à 09:42'}</p></div>)}</div><Box title="Erreurs d’import"><DataTable headers={['Source','Date','Message','Statut','Détail']} rows={[['Meta Lead Ads','24 sept. · 14:32','Téléphone manquant','En erreur'],['Formulaire site','22 sept. · 11:08','Code postal invalide','Résolu']].map(r=>({key:String(r[0]),cells:[r[0],r[1],r[2],<Badge>{errorStates[String(r[0])]??r[3]}</Badge>,<span className="text-primary">Voir le détail</span>]}))} onRow={key=>{setErrorRow(key);setModal('error')}}/></Box></div>}
 {view==='journal'&&<Box title="Activité récente" action={<span className="text-xs text-muted-foreground">{journalRows.length} entrées</span>}>
  <div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-2.5 text-muted-foreground"/><Input value={journalQ} onChange={e=>setJournalQ(e.target.value)} placeholder="Rechercher un objet, une action…" className="pl-9"/></div>
  <select aria-label="Filtrer par utilisateur" value={journalUser} onChange={e=>setJournalUser(e.target.value)} className="h-9 rounded-md border border-border bg-background px-3 text-xs">{['Tous les utilisateurs',...new Set(log.map(l=>l.user))].map(o=><option key={o}>{o}</option>)}</select>
  <select aria-label="Filtrer par action" value={journalAction} onChange={e=>setJournalAction(e.target.value)} className="h-9 rounded-md border border-border bg-background px-3 text-xs">{['Toutes les actions',...new Set(log.map(l=>l.action))].map(o=><option key={o}>{o}</option>)}</select>
  <Button variant="outline" size="sm" onClick={()=>{setJournalQ('');setJournalUser('Tous les utilisateurs');setJournalAction('Toutes les actions')}}>Réinitialiser</Button></div>
  <DataTable headers={['Utilisateur','Action','Date / heure','Objet modifié','Nouvelle valeur']} rows={journalRows.map((r,i)=>({key:String(i),cells:[r.user,r.action,r.when,r.target,r.target]}))}/></Box>}
 </div>}</main>
 {modal&&<Dialog open onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent><DialogHeader><DialogTitle>{modal==='error'?'Détail de l’erreur':'Modifier les paramètres'}</DialogTitle><DialogDescription>{modal==='error'?'L’import a échoué car une donnée obligatoire est absente.':'Aperçu interactif OEKO.'}</DialogDescription></DialogHeader>{modal==='settings'?<><div><Label>Nouvel élément · {settingsGroup}</Label><Input value={settingsDraft} onChange={e=>setSettingsDraft(e.target.value)} placeholder="Ex. : Nouveau motif de perte"/></div><Button onClick={()=>{const value=settingsDraft.trim();if(!value){notify('Saisissez un libellé.');return}setExtraSettings(p=>({...p,[settingsGroup]:[...(p[settingsGroup]??[]),value]}));addLog('A modifié les paramètres',`${settingsGroup} · ${value}`);notify('Paramètre ajouté.');setModal(null)}}>Ajouter</Button></>:<><div className="space-y-2 rounded-md border border-border bg-canvas p-4 text-xs"><p><span className="font-bold">Source :</span> {errorRow}</p><p><span className="font-bold">Date :</span> 24 sept. 2026 · 14:32</p><p><span className="font-bold">Identifiant technique :</span> evt_lead_9f4c21e7 (démonstration)</p><p><span className="font-bold">Statut :</span> {errorStates[errorRow]??'En erreur'}{retryState[errorRow]?` · ${retryState[errorRow]}`:''}</p><div><p className="font-bold">Données reçues :</p><pre className="mt-1 overflow-x-auto rounded bg-background p-3 text-[11px]">{`{
  "full_name": "Karim Ferrand",
  "phone": null,
  "email": "karim.ferrand@example.fr",
  "city": "Aulnay-sous-Bois",
  "service": "Pompe à chaleur"
}`}</pre></div><div><p className="font-bold">Historique :</p><ul className="mt-1 list-disc pl-4 text-muted-foreground"><li>24 sept. 14:32 · Import refusé (téléphone manquant)</li><li>24 sept. 14:35 · Notification envoyée à l’équipe qualification</li>{retryState[errorRow]&&<li>Aujourd’hui · Nouvelle tentative lancée</li>}{errorStates[errorRow]==='Résolu'&&<li>Aujourd’hui · Erreur marquée comme résolue</li>}</ul></div></div><Field label="Commentaire" type="textarea"/><div className="flex flex-wrap gap-2"><Button onClick={()=>{setErrorStates(p=>({...p,[errorRow]:'Résolu'}));addLog('A résolu une erreur d’import',errorRow);notify('Erreur marquée comme résolue.');setModal(null)}}>Marquer comme résolu</Button><Button variant="outline" onClick={()=>{setRetryState(p=>({...p,[errorRow]:'Nouvelle tentative en cours'}));addLog('A relancé un import',errorRow);notify('Nouvelle tentative d’import lancée.')}}>Réessayer l’import</Button><Button variant="ghost" onClick={()=>setModal(null)}>Fermer</Button></div></>}</DialogContent></Dialog>}
  {mediaIndex!==null&&<Dialog open onOpenChange={open=>{if(!open)setMediaIndex(null)}}><DialogContent><DialogHeader><DialogTitle>Détails du média</DialogTitle><DialogDescription>Gérez le nom et le texte alternatif de cette image.</DialogDescription></DialogHeader><img src={chantierImage} width={1200} height={800} loading="lazy" alt="Chantier de rénovation" className="aspect-video w-full rounded object-cover"/><div><Label>Nom du fichier</Label><Input value={mediaDraft} onChange={e=>setMediaDraft(e.target.value)}/></div><div><Label>Texte alternatif</Label><Input value={mediaAlt} onChange={e=>setMediaAlt(e.target.value)}/></div><div><Label>Rattacher à</Label><select value={mediaUse} onChange={e=>setMediaUse(e.target.value)} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm">{['Article de blog','Service','Réalisation','Dossier client'].map(o=><option key={o}>{o}</option>)}</select></div><div className="flex flex-wrap gap-2"><Button onClick={()=>{const current=mediaNames[mediaIndex!]??'';setMediaNames(prev=>prev.map((name,i)=>i===mediaIndex?mediaDraft||name:name));addLog('A renommé un média',mediaDraft||current);notify(`Média mis à jour et rattaché à : ${mediaUse}.`);setMediaIndex(null)}}>Enregistrer</Button><Button variant="outline" onClick={()=>{const current=mediaNames[mediaIndex!]??'';const on=mediaArchived.includes(current);setMediaArchived(p=>on?p.filter(x=>x!==current):[...p,current]);addLog(on?'A restauré un média':'A archivé un média',current);notify(on?'Média restauré.':'Média archivé.');setMediaIndex(null)}}>{mediaArchived.includes(mediaNames[mediaIndex!]??'')?'Restaurer':'Archiver'}</Button><Button variant="outline" asChild><a href={chantierImage} download><Download size={15}/>Télécharger</a></Button><Button variant="ghost" className="text-destructive" onClick={()=>{const current=mediaNames[mediaIndex!]??'';setMediaNames(p=>p.filter(x=>x!==current));addLog('A supprimé un média',current);notify('Média supprimé (simulation).');setMediaIndex(null)}}>Supprimer</Button></div></DialogContent></Dialog>}
 {toast&&<div role="status" className="fixed bottom-5 right-5 z-[70] flex max-w-[calc(100vw-2rem)] items-center gap-2 rounded-md bg-primary px-4 py-3 text-xs font-semibold text-primary-foreground shadow-lg"><Check size={16}/>{toast}</div>}
 </div>
}
function MiniStat({label,value,change}:{label:string;value:string;change:string}){return <div className="rounded-lg border border-border bg-background p-5"><p className="text-xs font-medium text-muted-foreground">{label}</p><div className="mt-3 text-2xl font-bold">{value}</div><p className="mt-2 text-[11px] font-semibold text-primary">{change}</p></div>}
function DayView({setSelected,go}:{setSelected:(l:Lead)=>void;go:(v:View)=>void}){const groups=[['Nouveaux dossiers','2','Foued Benali · Isolation extérieure','Marc Lefèvre · Ravalement façade'],['À rappeler','3','Laurent Dubois · 16:00','Nadia Bensalem · 11:00'],['Rendez-vous','2','Camille Petit · 10:00','Foued Benali · 14:30'],['Devis à faire','2','Sofia Rahmani · Climatisation','Camille Petit · Toiture'],['Devis à relancer','4','Nadia Bensalem · Menuiseries','Laurent Dubois · Pompe à chaleur'],['Actions en retard','2','Marc Lefèvre · Qualification','Nadia Bensalem · Relance']];return <div className="grid gap-5 lg:grid-cols-2">{groups.map(([title,num,...items],i)=><Box key={title ?? "section"} title={title ?? "Actions"} action={<span className="rounded bg-lime/40 px-2 py-0.5 text-xs font-bold">{num}</span>}><div className="divide-y divide-border">{items.map((item,j)=><div key={item} onClick={()=>{const l=seedLeads.find(x=>item.includes(x.name));if(l)setSelected(l);else go('devis')}} className="flex cursor-pointer items-center gap-3 px-5 py-4 hover:bg-canvas"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-secondary text-primary">{i<2?<Users size={16}/>:i===2?<CalendarDays size={16}/>:<FileText size={16}/>}</span><span className="min-w-0 flex-1 truncate text-xs font-semibold">{item}</span><ArrowRight size={15} className="text-muted-foreground"/></div>)}</div></Box>)}</div>}
function ContentList({kind,search,setSearch,openItem,entries}:{kind:'articles'|'services'|'realisations';search:string;setSearch:(v:string)=>void;openItem:(item:string)=>void;entries:{section:string;title:string;detail:string;date:string;status:string}[]}){const {articleList}=useOekoDemo();const [status,setStatus]=useState('Tous les statuts');const data:Row[]=kind==='articles'?articleList.map(a=>({name:a.title,detail:a.type,date:a.date,status:a.status,extra:a.author})):kind==='services'?services.map((s,i)=>({name:s,detail:['Ravalement et isolation','Réfection et isolation','Isolation thermique par l’extérieur','Chauffage performant','Confort été et hiver','Fenêtres et portes'][i] ?? '',date:`${20-i} sept. 2026`,status:i===5?'Brouillon':'Publié',extra:'OEKO'})):[{name:'Rénovation de façade à Créteil',detail:'Créteil · 94',date:'18 sept. 2026',status:'Publié',extra:'Façade'},{name:'Isolation d’une maison à Versailles',detail:'Versailles · 78',date:'12 sept. 2026',status:'Publié',extra:'ITE'},{name:'Toiture rénovée à Montreuil',detail:'Montreuil · 93',date:'8 sept. 2026',status:'Brouillon',extra:'Toiture'},{name:'Installation PAC à Cergy',detail:'Cergy · 95',date:'2 sept. 2026',status:'Publié',extra:'PAC'}];const combined=[...entries.filter(e=>e.section===kind&&kind!=='articles').map(e=>({name:e.title,detail:e.detail,date:e.date,status:e.status,extra:'OEKO'})),...data];const filtered=combined.filter(r=>`${r.name} ${r.detail}`.toLowerCase().includes(search.toLowerCase())&&(status==='Tous les statuts'||r.status===status));return <Box title={kind==='articles'?'Tous les articles':kind==='services'?'Catalogue de services':'Chantiers réalisés'} action={<span className="text-xs text-muted-foreground">{filtered.length} éléments</span>}><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-2.5 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher..." className="pl-9"/></div><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filtrer par statut" className="h-9 rounded-md border border-border bg-background px-3 text-xs"><option>Tous les statuts</option><option>Publié</option><option>Brouillon</option></select></div><DataTable headers={kind==='articles'?['Titre','Catégorie','Auteur','Date','Statut','']:kind==='services'?['Service','Description','Responsable','Date','Statut','']:['Réalisation','Ville / Département','Service','Date','Statut','']} rows={filtered.map((r,i)=>({key:r.name,cells:[<span className="flex items-center gap-3 font-bold">{kind==='realisations'&&<img src={chantierImage} width={1200} height={800} loading="lazy" alt="Maison rénovée" className="size-9 rounded object-cover"/>}{r.name}</span>,r.detail,r.extra,r.date,<Badge>{r.status}</Badge>,<ArrowRight size={15} className="text-primary"/>]}))} onRow={openItem}/></Box>}
